NSCC-ITC-Winter2025-WEBD3031-700-MCa/webd3031-project-famlilyconnect

package.json
=> Fix: change npm to pnpm for adding depenences

README.md
=> docs: update README with project details

src/components/Header/index.tsx, src/components/Header/menuData.tsx, src/middleware.ts, src/types/menu.ts
- Created nav link for Admin
- Admin link in nav bar is only visible for accounts with admin role
- protected routes starting with /admin if not logged in
closes #30
=> 30: Add login to Admin Dashboard

src/app/api/members/route.ts, src/components/admin/member-table.tsx
- Fetched users from DB
- Populated users table in the admin dashboard with DB info
closes #31
=> 31: Fetch Users from DB

src/components/admin/app-sidebar.tsx
- Added back button to the admin sidebar to take you back to main site.
closes #50
=> feat(add-back-btn): added back button at admin sidebar

src/app/api/family/[id]/image/[photoId]/route.ts, src/app/api/family/[id]/image/route.ts, src/app/api/family/[id]/route.ts, src/components/FamilyDetail/PhotoGallery.tsx, src/components/FamilyDetail/index.tsx, src/components/ManageFamily/index.tsx
=> feat: add family photos page functions

prisma/migrations/20250325173639_edit_event_table/migration.sql, prisma/schema.prisma, src/app/api/family/[id]/event/[eventId]/route.ts, src/app/api/family/[id]/event/route.ts, src/app/api/family/[id]/route.ts, src/components/Event/CreateEventForm.tsx, src/components/Event/index.tsx, src/components/FamilyDetail/index.tsx, src/styles/index.css
=> feat: add manage events part

src/app/api/family/[id]/member/[memberId]/role/route.ts, src/app/api/family/[id]/member/[memberId]/route.ts, src/app/api/family/[id]/route.ts, src/components/Event/CreateEventForm.tsx, src/components/Event/index.tsx, src/components/FamilyDetail/PhotoGallery.tsx, src/components/FamilyDetail/index.tsx, src/components/FamilyMember/index.tsx, src/components/ManageFamily/InviteMember.tsx, src/components/ManageFamily/index.tsx, src/components/Post/CreatePost.tsx, src/components/Post/index.tsx, src/components/Profile/index.tsx, src/middleware.ts, src/utils/roles.ts
=> feat: add manage member part

src/app/api/family/[id]/route.ts, src/components/Profile/index.tsx
=> fix(theme, groups): correct theme color and improve group management

src/app/api/contact/route.ts, src/components/Contact/index.tsx, src/utils/email.ts
=> feat: add contact page function

src/components/admin/app-sidebar.tsx
Added functionality to the logout button in the admin sidebar panel
fixes #34
=> feat: added logout functionality

src/components/Hero/index.tsx
=> fix: hero image not showing on deploy site

src/app/(site)/admin/members/page.tsx, src/components/admin/member-table.tsx
added functionality to search bar to filter through the members list
fixes #32
=> 32 search bar

src/app/(site)/admin/members/view/[id]/page.tsx, src/app/api/members/[id]/familymember/route.ts
Create endpoint to fetch family member data 
Added a table to display family member data
fixes #93
=> 93 admin family member

src/app/(site)/admin/members/view/[id]/page.tsx, src/app/api/members/[id]/userposts/route.ts
created api endpoint to fetch user posts
created table to display user posts in the members view 
fixes #94
=> 94 admin user posts

prisma/schema.prisma, src/app/(site)/admin/members/view/[id]/page.tsx
fixed the posts adding a new table for each post
fixes #106
=> fix: fixed posts adding new table per post

src/components/ui/sidebar.tsx
changed the sidebar from transparent to white. Sidebar is no longer see through when scrolling horizontally
fixes #107
=> fix: changed the sidebar from transparent

src/app/api/payment/subscription/route.ts, src/app/api/payment/webhook/route.ts
=> Usersubrestrict

src/components/Profile/index.tsx, src/utils/auth.ts
=> fix: fix the logout bug in profilePage

src/components/ui/sidebar.tsx
fixed admin side bar from being white in dark mode
fixes #122
=> fix: changed admin sidebar to black on darkmode

src/app/(site)/admin/members/view/[id]/page.tsx, src/app/api/members/[id]/family/route.ts
added endpoint for family table
added family table to the members view page
fixes #92
=> added family details to view

src/components/Features/index.tsx
change feature title from play to family connect 
fixes #110
=> fix: changed features title

src/components/Auth/SignIn/index.tsx, src/components/Header/index.tsx, src/components/Header/menuData.tsx, src/components/ManageFamily/index.tsx, src/middleware.ts, src/types/menu.ts
=> fix middleware relative family page

src/app/(site)/admin/members/view/[id]/page.tsx, src/app/api/members/[id]/route.ts, src/components/admin/app-sidebar.tsx
added isPremium to user details in the member view
fixes #134
=> feat: added isPremium to user details table
